---
title: "Zomato - Best of Melbourne Analysis"
author:
- familyname: Editya
  othernames: Dea Avega
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications: Master of BA 
- familyname: Qasim
  othernames: Muhammad Soban
  address: Monash University
  qualifications: Master of BA
- familyname: Sinha 
  othernames: Abhishek
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications:  Master of BA
- familyname: Vu 
  othernames: Vinny
  address: Monash University
  email: vvuu0009@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of BA
department: Our consultancy \newline add names &\newline add names
organization: ETC5513 Collaborative and Reproductible Practices 
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache=FALSE, 
                      messages=FALSE, 
                      warning=FALSE)

library(romato)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(leaflet)
library(rgdal)
library(readr)
library(mapview)
library(viridis)
library(kableExtra)
library(knitr)
```

\section*{Popularity of different cuisines in Melbourne} 

```{r assigning API, echo = FALSE, include = FALSE, message = FALSE, warning = FALSE}
zmt <- zomato$new("1623b413d3a1614e765de7578f83a10b") #assign API key
```

# Get the data from romato

```{r read data, echo = FALSE, include = FALSE, message = FALSE, warning = FALSE}

# pull data for category "Best of Melbourne" using Melbourne ID "259"
melb <- zmt$search(entity_id = "259", entity_type = "city", category = "Best of Melbourne") 

#search restaurant around CBD
melb_cbd <- melb %>% 
  filter(locality == "CBD") %>% 
  mutate(aggregate_rating = as.numeric(aggregate_rating), price_range = as.numeric(price_range), longitude = as.numeric(longitude), latitude = as.numeric(latitude))

melb_top100 <- melb %>% 
  mutate(aggregate_rating = as.numeric(aggregate_rating), price_range = as.numeric(price_range), longitude = as.numeric(longitude), latitude = as.numeric(latitude))

```




